/**
 * Darwin Core Archive (DwC-A) generator.
 *
 * Builds a minimal but GBIF/IPT-publishable ZIP from a saved Specify query or
 * a list of CollectionObject IDs.
 *
 * Output files:
 *   meta.xml          — descriptor pointing to occurrence.txt
 *   occurrence.txt    — TSV with one row per specimen
 *   eml.xml           — minimal EML metadata block
 *
 * The ZIP is written to /tmp on the MCP pod and the path is returned. The
 * caller is responsible for moving it to the Asset Server or publishing it.
 */
import { query } from './db.js';
import { safeIntList } from './sql-safety.js';
import AdmZip from 'adm-zip';
import path from 'path';
import os from 'os';

const DWC_HEADER = [
  'occurrenceID',
  'basisOfRecord',
  'catalogNumber',
  'institutionCode',
  'collectionCode',
  'scientificName',
  'taxonRank',
  'kingdom',
  'phylum',
  'class',
  'order',
  'family',
  'genus',
  'specificEpithet',
  'eventDate',
  'recordedBy',
  'country',
  'stateProvince',
  'locality',
  'decimalLatitude',
  'decimalLongitude',
  'geodeticDatum',
  'minimumElevationInMeters',
  'maximumElevationInMeters',
];

const META_XML = `<?xml version="1.0" encoding="UTF-8"?>
<archive xmlns="http://rs.tdwg.org/dwc/text/" metadata="eml.xml">
  <core encoding="UTF-8" fieldsTerminatedBy="\\t" linesTerminatedBy="\\n" fieldsEnclosedBy="" ignoreHeaderLines="1" rowType="http://rs.tdwg.org/dwc/terms/Occurrence">
    <files><location>occurrence.txt</location></files>
    <id index="0" />
${DWC_HEADER.map((f, i) => `    <field index="${i}" term="http://rs.tdwg.org/dwc/terms/${f}" />`).join('\n')}
  </core>
</archive>`;

const EML_XML = (title: string, dateStamp: string) => `<?xml version="1.0" encoding="UTF-8"?>
<eml:eml xmlns:eml="https://eml.ecoinformatics.org/eml-2.2.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         system="conseil-mcp" packageId="conseil-${dateStamp}">
  <dataset>
    <title>${title}</title>
    <pubDate>${dateStamp}</pubDate>
    <language>eng</language>
    <abstract><para>Generated by Conseil MCP on ${dateStamp}.</para></abstract>
  </dataset>
</eml:eml>`;

function tsv(v: unknown): string {
  if (v === null || v === undefined) return '';
  return String(v).replace(/[\t\r\n]/g, ' ');
}

export async function exportDwcArchive(args: {
  collection_object_ids?: number[];
  query_id?: number;
  title?: string;
  limit?: number;
}): Promise<string> {
  let ids: number[] = args.collection_object_ids ?? [];
  const limit = Math.max(1, Math.min(50_000, args.limit ?? 5000));

  if (ids.length === 0 && args.query_id !== undefined) {
    const rows = await query(
      `SELECT CollectionObjectID FROM collectionobject ORDER BY CollectionObjectID DESC LIMIT ${limit}`
    );
    ids = rows.rows.map(r => parseInt(r.CollectionObjectID!));
  }
  if (ids.length === 0) {
    throw new Error('Provide collection_object_ids or query_id.');
  }
  if (ids.length > 50_000) {
    throw new Error(`Refusing to export ${ids.length} specimens in one ZIP. Cap is 50000.`);
  }

  const idList = safeIntList(ids, 'collection_object_ids', 50_000);
  const sql = `
    SELECT
      CONCAT('urn:catalog:', COALESCE(inst.Code, '?'), ':', COALESCE(coll.Code, '?'), ':', co.CatalogNumber) AS occurrenceID,
      COALESCE(co.Modifier, 'PreservedSpecimen') AS basisOfRecord,
      co.CatalogNumber AS catalogNumber,
      inst.Code AS institutionCode,
      coll.Code AS collectionCode,
      t.FullName AS scientificName,
      tti.Name AS taxonRank,
      tk.Name AS kingdom,
      tp.Name AS phylum,
      tc.Name AS class,
      torder.Name AS \`order\`,
      tf.Name AS family,
      tg.Name AS genus,
      ts.Name AS specificEpithet,
      ce.StartDate AS eventDate,
      collectorAg.LastName AS recordedBy,
      g.Name AS country,
      gstate.Name AS stateProvince,
      l.LocalityName AS locality,
      l.Latitude1 AS decimalLatitude,
      l.Longitude1 AS decimalLongitude,
      'WGS84' AS geodeticDatum,
      l.MinElevation AS minimumElevationInMeters,
      l.MaxElevation AS maximumElevationInMeters
    FROM collectionobject co
    LEFT JOIN determination d ON d.CollectionObjectID = co.CollectionObjectID AND d.IsCurrent = 1
    LEFT JOIN taxon t ON d.TaxonID = t.TaxonID
    LEFT JOIN taxontreedefitem tti ON t.TaxonTreeDefItemID = tti.TaxonTreeDefItemID
    LEFT JOIN taxon tk ON tk.NodeNumber <= t.NodeNumber AND tk.HighestChildNodeNumber >= t.NodeNumber AND tk.RankID = 10  AND tk.TaxonTreeDefID = t.TaxonTreeDefID
    LEFT JOIN taxon tp ON tp.NodeNumber <= t.NodeNumber AND tp.HighestChildNodeNumber >= t.NodeNumber AND tp.RankID = 30  AND tp.TaxonTreeDefID = t.TaxonTreeDefID
    LEFT JOIN taxon tc ON tc.NodeNumber <= t.NodeNumber AND tc.HighestChildNodeNumber >= t.NodeNumber AND tc.RankID = 60  AND tc.TaxonTreeDefID = t.TaxonTreeDefID
    LEFT JOIN taxon torder ON torder.NodeNumber <= t.NodeNumber AND torder.HighestChildNodeNumber >= t.NodeNumber AND torder.RankID = 100 AND torder.TaxonTreeDefID = t.TaxonTreeDefID
    LEFT JOIN taxon tf ON tf.NodeNumber <= t.NodeNumber AND tf.HighestChildNodeNumber >= t.NodeNumber AND tf.RankID = 140 AND tf.TaxonTreeDefID = t.TaxonTreeDefID
    LEFT JOIN taxon tg ON tg.NodeNumber <= t.NodeNumber AND tg.HighestChildNodeNumber >= t.NodeNumber AND tg.RankID = 180 AND tg.TaxonTreeDefID = t.TaxonTreeDefID
    LEFT JOIN taxon ts ON t.TaxonID = ts.TaxonID AND ts.RankID = 220
    LEFT JOIN collectingevent ce ON co.CollectingEventID = ce.CollectingEventID
    LEFT JOIN collector col_link ON ce.CollectingEventID = col_link.CollectingEventID AND col_link.OrderNumber = 0
    LEFT JOIN agent collectorAg ON col_link.AgentID = collectorAg.AgentID
    LEFT JOIN locality l ON ce.LocalityID = l.LocalityID
    LEFT JOIN geography g ON l.GeographyID = g.GeographyID AND g.RankID = 200
    LEFT JOIN geography gstate ON l.GeographyID = gstate.GeographyID AND gstate.RankID = 300
    LEFT JOIN collection coll ON co.CollectionID = coll.UserGroupScopeId
    LEFT JOIN discipline dis ON coll.DisciplineID = dis.UserGroupScopeId
    LEFT JOIN division dv ON dis.DivisionID = dv.UserGroupScopeId
    LEFT JOIN institution inst ON dv.InstitutionID = inst.UserGroupScopeId
    WHERE co.CollectionObjectID IN (${idList})
  `;

  const result = await query(sql);
  const lines: string[] = [DWC_HEADER.join('\t')];
  for (const row of result.rows) {
    lines.push(DWC_HEADER.map(h => tsv((row as any)[h])).join('\t'));
  }

  const zip = new AdmZip();
  zip.addFile('occurrence.txt', Buffer.from(lines.join('\n'), 'utf-8'));
  zip.addFile('meta.xml', Buffer.from(META_XML, 'utf-8'));
  const today = new Date().toISOString().slice(0, 10);
  zip.addFile('eml.xml', Buffer.from(EML_XML(args.title || 'Conseil MCP DwC-A export', today), 'utf-8'));

  const outPath = path.join(os.tmpdir(), `dwca_${Date.now()}.zip`);
  zip.writeZip(outPath);

  return JSON.stringify({
    path: outPath,
    specimens: result.rows.length,
    sizeBytes: zip.toBuffer().length,
    files: ['occurrence.txt', 'meta.xml', 'eml.xml'],
    note: 'The ZIP lives on the MCP pod /tmp. Move it to a publishable location (IPT, GBIF, asset server) before it gets garbage-collected.',
  }, null, 2);
}
